run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck

linters-settings:
  govet:
    enable-all: true

issues:
  exclude-rules:
    - path: internal/telemetry
      linters:
        - goanalysis_metalinter
